package={name='vector', version='0.0.0',edition='2021', rust-version='1.79'}
lib={path='lib.rs'}

[features]
int_roundings=['num/int_roundings']

[dependencies]
num={git='https://github.com/Matthias-Fauconneau/num'}
bytemuck='*'
serde={version='*', optional=true, features=['derive']}
